#cloud-config

coreos:
  
  etcd2:

    # get a token https://discovery.etcd.io/new?size=3 
    # size = how many etcd cluster nodes
    discovery: "https://discovery.etcd.io/ADD-YOUR-TOKEN-HERE"
    advertise-client-urls: "http://$public_ipv4:2379"
    initial-advertise-peer-urls: "http://$private_ipv4:2380"
    listen-client-urls: "http://0.0.0.0:2379,http://0.0.0.0:4001"
    listen-peer-urls: "http://$private_ipv4:2380,http://$private_ipv4:7001"

  update:
    reboot-strategy: "etcd-lock"

  units:
    - name: "etcd2.service"
      command: "start"
      enable:  true

write-files:
  
  - path: "/home/core/.bash_profile"
    permissions: "0644"
    content: |
      alias l="ls -alF"
      alias ..="cd .."

  - path: "/root/.bash_profile"
    permissions: "0644"
    content: |
      alias l="ls -alF"
      alias ..="cd .."
